name: fitapp

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Ícones
  cupertino_icons: ^1.0.8

  # Logs
  logger: ^2.0.2

  # Banco de dados local
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+2
  path_provider: ^2.1.2
  path: ^1.8.3

  # Estado e UI
  provider: ^6.1.2
  flutter_slidable: ^4.0.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  # Social Login
  google_sign_in: ^6.2.1

  # SVG Support
  flutter_svg: ^2.0.9

  # Image Picker
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  
  # URL Launcher
  url_launcher: ^6.2.5
  # health: ^8.1.0  # Temporariamente comentado devido a problemas de compatibilidade
  # flutter_local_notifications: ^16.1.0  # Temporariamente comentado devido a problemas de compatibilidade
  intl: ^0.18.0

  # Calendar
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/dumbbells_bg.jpg
    - assets/images/google_logo.svg
    - assets/images/instagram_icon.svg
    - assets/images/tiktok_icon.svg
    - assets/images/twitter_icon.svg
    - assets/images/rat_1.jpg
    - assets/images/rat_2.jpg
    - assets/images/rat_3.jpg
    - assets/images/rat_4.jpg
    - assets/images/rat_5.jpg
    - assets/images/rat_6.jpg
    - assets/animations/
