// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP5fEvPOelMJLOIJ58rO6PkIMBIAKvhsA',
    appId: '1:707846215547:web:4bf8de7d3539996f8f0fde',
    messagingSenderId: '707846215547',
    projectId: 'academia-173e0',
    authDomain: 'academia-173e0.firebaseapp.com',
    storageBucket: 'academia-173e0.appspot.com', // ✅ corrigido
    measurementId: 'G-3T1ZF1RPC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnfupeGpyziAikPPcmw6acspzMr33Efbc',
    appId: '1:707846215547:android:886fdbb836e887618f0fde',
    messagingSenderId: '707846215547',
    projectId: 'academia-173e0',
    storageBucket: 'academia-173e0.appspot.com', // ✅ corrigido
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsP3YgwWyKFp67GcG_ygYh-En7BPoi1Yg',
    appId: '1:707846215547:ios:2a212b3e664cf44d8f0fde',
    messagingSenderId: '707846215547',
    projectId: 'academia-173e0',
    storageBucket: 'academia-173e0.appspot.com', // ✅ corrigido
    iosBundleId: 'com.example.fitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP5fEvPOelMJLOIJ58rO6PkIMBIAKvhsA',
    appId: '1:707846215547:web:35aee906fdb7d9898f0fde',
    messagingSenderId: '707846215547',
    projectId: 'academia-173e0',
    authDomain: 'academia-173e0.firebaseapp.com',
    storageBucket: 'academia-173e0.appspot.com', // ✅ corrigido
    measurementId: 'G-KJFX6KPXN3',
  );
}
